version: '3.8'

services:
  apache:
    image: httpd
    ports:
      - "80:80"
    volumes:
      - /cursodio/web/site:/usr/local/apache2/htdocs/
    networks:
      - minha-rede
networks:
  minha-rede:
    driver: bridge
